name: popInf_environment
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
dependencies:
  - python=3.5.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - vcftools=0.1.14
  - plink=1.90b4
  - gatk=3.7
  - eigensoft=6.0.1
  - tabix
  - r-essentials
  - bedtools=2.24.0
