# Snakefile to prepare the reference panel for input into popInf
import os

configfile: "prep_ref.config.json"


rule all:
	input:
		expand("chr{chrm}_reference_panel.vcf.gz", chrm=config["chromosome"]),
		expand("chr{chrm}_reference_panel.vcf.gz.tbi", chrm=config["chromosome"])


rule subset_1000genomes:
    input:
        gzvcf = (config["vcf_1000g_path"] + config["input_vcf_prefix"] + "{chrm}" + config["input_vcf_suffix"]),
        inds = config["pop_list_1000g"]
    output:
        "chr{chrm}_reference_panel.vcf.gz"
    shell:"""
        vcftools --gzvcf {input.gzvcf} --keep {input.inds} --stdout | bgzip -c > {output}

	"""

rule tabix:
	input:
		"chr{chrm}_reference_panel.vcf.gz"
	output:
		"chr{chrm}_reference_panel.vcf.gz.tbi"
	shell:
		"tabix -p vcf {input}"
